version: 2
project_name: wkv
builds:
  - main: ./cmd/wkv
    binary: wkv
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: [-s -w]
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
brews:
  - repository:
      owner: sorafujitani
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/sorafujitani/wezterm-keymap-viewer"
    description: "Fuzzy-searchable TUI viewer for wezterm keybindings"
    license: "MIT"
    caveats: "wkv requires wezterm to be installed and available in your PATH."
